# Generated by Django 5.2 on 2025-05-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_remove_image_title_image_patient_image_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
