# Generated by Django 5.2 on 2025-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_alter_patient_contact_number_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_images/'),
        ),
    ]
