# Generated by Django 5.1.5 on 2025-05-15 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 15, 15, 32, 47, 987810, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
