# Generated by Django 5.1.5 on 2025-05-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_image_annotated_image'),
        ('annotations', '0006_alter_patient_created_at'),
    ]

    operations = [
    ]
