# Generated by Django 5.1.5 on 2025-05-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_merge_20250518_2011'),
        ('annotations', '0007_merge_20250519_2020'),
    ]

    operations = [
    ]
