# Generated by Django 5.1.5 on 2025-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0013_alter_patient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='baranggay',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_municipality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
