# Generated by Django 5.2 on 2025-05-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0016_patient_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='procedure',
        ),
    ]
