# Generated by Django 5.2 on 2025-05-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0017_remove_patient_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='procedure',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
