# Generated by Django 5.1.5 on 2025-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0019_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_municipality_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='patient',
            name='province_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='patient',
            name='region_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='patient',
            name='baranggay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_municipality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
